service: apigw-echo
provider:
  name: aws
  runtime: python3.7
  profile: sandbox
  stage: ${opt:stage, 'develop'}
  apiKeys:
    - name: ${self:service}-${self:provider.stage}-mainKey

functions:
  echo:
    handler: handler.echo
    events:
      - http:
            method: GET
            path: /echo
            private: true
